### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by wSedlacek** [nordfjord/nestjs-cqrs-es-example-app#2]
Right now this project is unlicensed, it would be nice if you could add a license to it, preferably MIT, so that it can be expanded upon and experimented with.

https://github.com/nordfjord/nestjs-cqrs-es-example-app/blob/c15d071efcf80b6f7b585c4e6dcd251bcea7e7cc/package.json#L7

**Comment by nordfjord** [comment]
Hi! Thanks for raising this, I've changed the license to "MIT" and added a license file!
